[WIP] 赤べこを動かすプログラムをリファクタリングする
AizuGeekDojo/akabeko_headban pull request #5
Opened 2020-10-15 01:42 UTC by hatobus

プログラムがあまりにも汚かったのでpythonのコードをリファクタリングします。

同様にREADMEにも変更を加えました。

手元に赤べこ等は無いのでこのブランチで動作確認してもらえると助かります :bow:

2020-10-26 07:46 UTC, wancom commented
WIPになってるけど修正終わりということで大丈夫？

2020-10-26 07:48 UTC, wancom requested changes
ちょっと変なところがあったので確認お願いします。

2020-10-26 07:48 UTC, wancom commented on connect_Raspi/comp.py
> +                time.sleep(60.0/60000*2)
多分ここ1抜けてるね
```suggestion
                time.sleep(60.0/160000*2)
```

2020-10-28 01:09 UTC, hatobus commented on connect_Raspi/comp.py
> +                time.sleep(60.0/60000*2)
抜けてますね〜ありがとう！直しました！

2020-10-28 01:09 UTC, hatobus commented
修正は終わっているのでWIP外しておきました

2020-10-28 01:10 UTC, wancom commented
@hatobus ありがとう！！！！

2020-10-28 01:10 UTC, hatobus commented
素早い。。。！

2020-10-28 01:11 UTC, wancom commented
ちょっとテストが済んでいないので今度やります！

2020-10-28 04:45 UTC, suzakutakumi commented
自分が今日、確認します

2020-10-28 04:55 UTC, hatobus commented
@suzakutakumi よろしくお願いします 🙇

2020-10-28 07:17 UTC, suzakutakumi requested changes
たぶんタイポです。

2020-10-28 07:17 UTC, suzakutakumi commented on connect_Raspi/comp.py
> +MUSIC_DIR = "/home/pi/akabeko_headban/music/"
```suggestion
MUSICDIR = "/home/pi/akabeko_headban/music/"
```

2020-10-28 07:23 UTC, suzakutakumi commented
上記したものを直したら、動きました。

2020-10-28 07:26 UTC, wancom commented on connect_Raspi/comp.py
> +MUSIC_DIR = "/home/pi/akabeko_headban/music/"
確かにここを直した方が良さそうですね。

2020-10-28 07:27 UTC, wancom commented on connect_Raspi/comp.py
> +MUSIC_DIR = "/home/pi/akabeko_headban/music/"
@hatobus 勝手にアップデートしちゃいます。

2020-10-28 07:28 UTC, wancom approved these changes
リファクタリングについては他には問題なさそうなのでLGTMです

2020-10-28 07:35 UTC, suzakutakumi commented
Approveしても大丈夫ですかね?

2020-10-28 07:36 UTC, wancom commented
大丈夫だと思います。

2020-10-28 07:54 UTC, suzakutakumi reviewed
正常に動作しました

2020-10-28 07:55 UTC, suzakutakumi approved these changes

2020-10-28 07:56 UTC, merged